name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '.github/workflows/build-and-release.yml') }}-${{ github.sha }}
          restore-keys: |
            gradle-${{ hashFiles('**/*.gradle*', '.github/workflows/build-and-release.yml') }}-

      - name: Build with Gradle
        run: sh gradlew --no-daemon --stacktrace --info jar

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: packaged-jars
          path: build/libs/*.jar

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: packaged-jars
          path: build/libs

      - name: Extract version from JAR filename
        id: jar_version
        run: |
          VERSION=$(ls build/libs/*.jar | sed -n -e "s/.*-\(.*\)\.jar/\1/p")
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          tag_name: ${{ steps.jar_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
